#!/usr/bin/env bash
set -euo pipefail
[ -f atlas/governance/sandbox/SANDBOX_DOCTRINE.md ]
[ -f atlas/governance/sandbox/SANDBOX_MECHANISMS_70.md ]
[ -f atlas/governance/sandbox/SANDBOX_CYCLE_PROTOCOL.md ]
[ -f atlas/governance/sandbox/SANDBOX_STOP_RULES.md ]
[ -f atlas/governance/sandbox/SANDBOX_BUDGET_GUARD.md ]
[ -f atlas/governance/sandbox/SANDBOX_NOTIFICATION_RULES.md ]
[ -f atlas/governance/sandbox/SANDBOX_ACCEPTANCE_MATRIX.md ]
[ -f atlas/sandbox/evolution/cycle_state.md ]
[ -f atlas/sandbox/evolution/cycle_log.md ]
[ -f atlas/sandbox/evolution/candidate_contract.md ]
[ -f atlas/sandbox/evolution/candidate_scorecard.md ]
[ -f atlas/sandbox/evolution/next_mission_recommendation.md ]
[ -f atlas/sandbox/plomberie/mechanism_matrix_plomberie.md ]
[ -f atlas/sandbox/plomberie/adversarial_cases_plomberie.md ]
[ -f atlas/sandbox/plomberie/regression_traps.md ]
[ -f scripts/atlas_sandbox_cycle.sh ]
[ -f scripts/atlas_sandbox_score_candidate.sh ]
[ -f scripts/atlas_sandbox_detect_plateau.sh ]
[ -f scripts/atlas_sandbox_notify.sh ]
[ -f scripts/atlas_sandbox_next_mission.sh ]
[ -f scripts/atlas_sandbox_print_report.sh ]
echo OK
