"""Canonical models/constants for ATLAS pipeline."""

REALITY_DEMO = "DEMO"
REALITY_MANUAL = "MANUAL"
REALITY_COLLECTED = "COLLECTED_FROM_URL"
REALITY_PARTIAL = "PARTIALLY_VERIFIED"
REALITY_HUMAN_CONFIRMED = "HUMAN_CONFIRMED"

PIPELINE_NEW = "NEW"
PIPELINE_CONTACTED = "CONTACTED"
PIPELINE_REJECTED = "REJECTED"

QUALIFICATION_BUSINESS_READY = "BUSINESS_READY"
QUALIFICATION_TO_VALIDATE = "TO_VALIDATE"

INTENT_BUSINESS = {"CLIENT_REQUEST", "PUBLIC_MARKET"}
INTENT_NON_READY = {"DIRECTORY_PAGE", "ARTISAN_AD", "GENERIC_PAGE", "UNKNOWN"}
